#pragma once

#define PROCESS_PROTECTOR_DEVICE 0x8000
#define IOCTL_PROCESS_PROTECT_BY_PID CTL_CODE(PROCESS_PROTECTOR_DEVICE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROCESS_UNPROTECT_BY_PID CTL_CODE(PROCESS_PROTECTOR_DEVICE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROCESS_PROTECT_CLEAR CTL_CODE(PROCESS_PROTECTOR_DEVICE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)